version: "3.9"

services: 
  bento:
    image: lewisdoesstuff/bento-next
    volumes:
      # Append Bento config location to below line.
      - /config.ts:/usr/share/nginx/html/config.ts
    ports:
      # Replace host port 80 (left side) with desired port.
      - 80:8080